POST http://localhost:3000/api/girl/add HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "id": 4,
  "name": "晓彤",
  "age": 17
}

###
Get http://localhost:3000/api/girl/getGirlById?id=1 HTTP/1.1

###
GET http://localhost:3000/api/girl/findGirlById/2/QT HTTP/1.1

###
GET http://localhost:3000/api/girl/delete/4 HTTP/1.1

###
GET http://localhost:3000/api/girl/update/1 HTTP/1.1

###
GET http://localhost:3000/api/girl HTTP/1.1

###
GET http://localhost:3000/api/girl/findGirlByName/晓 HTTP/1.1